# Generated by Django 5.0.6 on 2024-06-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="slug"
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="blog/photo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "publication_sign",
                    models.BooleanField(default=True, verbose_name="Опубликовать"),
                ),
                (
                    "number_of_views",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
