# Generated by Django 4.2.2 on 2024-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_sign",
            field=models.BooleanField(
                default=False,
                help_text="Укажите признак публикации",
                verbose_name="Признак публикации",
            ),
        ),
    ]
