# Generated by Django 4.2.2 on 2024-06-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_publication_sign"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price", "created_at", "updated_at"],
                "permissions": [
                    ("can_edit_publication_sign", "Can edit publication sign"),
                    ("can_edit_description", "Can edit description"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
